version: "3.9"
services:
  api:
    build: ./backend
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./wordlists:/wordlists
    ports:
      - "8080:8080"
    depends_on:
      - redis
  worker:
    build: ./worker
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./wordlists:/wordlists
    depends_on:
      - redis
  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "5173:5173"
    depends_on:
      - api
  redis:
    image: redis:7
    ports:
      - "6379:6379"
